
export const REGISTER_EMPLOYEE_ERROR = "REGISTER_EMPLOYEE_ERROR";

export const REGISTER_EMPLOYEE_SUCCESS = "REGISTER_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE__SUCCESS = "GET_EMPLOYEE__SUCCESS";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const FETCH_SINGLE_EMPLOYEE = "FETCH_SINGLE_EMPLOYEE";





